language: java
jdk: openjdk11

env:
  - IMG=kiwigrid/keycloak-client-controller

deploy:
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash .travis/deploy.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true